# Generated by Django 3.1.3 on 2020-11-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcelu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='Color',
            field=models.CharField(max_length=150),
        ),
    ]
